### PR TITLE
Adding space to status code when 403

### PR DESCRIPTION
**Pull request by Yoroitchi**
This pull request aims to solve #54

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the PR!

The space at the end of the string looks a bit off...

The `status` values (of type String) are in the end passed to and processed by the `satosa.response.Response`  class - which in values defined internally use the syntax `"<code> <reason>"` - e.g., `"404 Not Found"` - see https://github.com/IdentityPython/SATOSA/blob/master/src/satosa/response.py#L95-L112

How about using `"403 Forbidden"` in this case?  It would make it clear why the space is there - and would match the use that already exists in SATOSA.

Cheers,
Vlad

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the change @Yoroitchi .  Looks like an easy fix good to merge to me @peppelinux

**Comment by Yoroitchi** [comment]
Hello @vladimir-mencl-eresearch,
Thank you for your review i did the changes following your advice.

**Review by peppelinux — APPROVED** [review]

**Comment by peppelinux** [comment]
Thank you @Yoroitchi

**Pull request merged**
