### PR TITLE
fix: use compare_digest when search by client_secret

### PR DESCRIPTION
**Pull request by melanger**

### CODE REVIEW

**Comment by peppelinux** [comment]
consider it merged @melanger 

I just need to ask you to change the version up to 3.1.0, since it is not a bugfix but an additional security feature that matters

**Comment by melanger** [comment]
> consider it merged @melanger
> 
> I just need to ask you to change the version up to 3.1.0, since it is not a bugfix but an additional security feature that matters

@peppelinux It's a security fix, it does not add any new behavior. https://semver.org/#spec-item-6

**Comment by peppelinux** [comment]
@melanger ok, just change the version in this PR so that the new release will be coerent with the version of semantic bot

**Comment by melanger** [comment]
> @melanger ok, just change the version in this PR so that the new release will be coerent with the version of semantic bot

semantic release will update the version number automatically :)

**Pull request merged**
