### PR TITLE
ci: semantic release

### PR DESCRIPTION
**Pull request by melanger**
TODO: set GitHub secrets
- [x] GITHUB_TOKEN according to https://github.com/semantic-release/github#github-authentication (personal token allowing to push to the repository)
- [x] PYPI_TOKEN according to https://gitlab.com/beepbeepgo/public/projects/semantic-release-python/-/tree/main/#environment-variables

This should start semantic release, which computes new version number based on conventional commit messages, updates setup.cfg with the new version, uploads the release to pypi.org and creates a GitHub release with release notes based on the commit messages.

It does not create changelog (may be added: https://github.com/semantic-release/changelog)

It does not wait for other workflows to be successful (even if another workflow fails, the release is created anyway). To stop semantic release on failure, it would need to be in the same workflow as the test jobs.

On first run, it should create version 0.7.0.

### CODE REVIEW

**Comment by peppelinux** [comment]
Hi @melanger , nice shot!

we have https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/main/.github/workflows/pypi.yml#L35
and https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/main/.github/workflows/release-drafter.yml#L17

I'm waiting your commits and ok before merge this

**Comment by melanger** [comment]
> Hi @melanger , nice shot!
> 
> we have https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/main/.github/workflows/pypi.yml#L35 and https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/blob/main/.github/workflows/release-drafter.yml#L17
> 
> I'm waiting your commits and ok before merge this

@peppelinux I cannot really test it, but it should be good to go.

**Comment by melanger** [comment]
@peppelinux Should be good to go. If any issues emerge after merging, I will try to create a fix afterwards.

**Comment by melanger** [comment]
It seems everything works fine, the release was created on GitHub and also published to Pypi.

**Pull request merged**
