### PR TITLE
v0.5.0

### PR DESCRIPTION
**Pull request by peppelinux**
- BREAKING CHANGE: oidcop session dump to mongodb as string
- fix: removed warning on mongodb operations (insert, get, count)
- feat: updated pymongo up to 4.0.1, retrocompatibility with pymongo 3.x indeed

### CODE REVIEW

**Comment by peppelinux** [comment]
@melanger feel free to put your kindly revision on this

**Comment by melanger** [comment]
> @melanger feel free to put your kindly revision on this

Looks reasonable, but it is a breaking change indeed, because old sessions in the database will cause errors when new version is deployed (because they cannot be read), if I understand it correctly. I recommend adding a changelog note that the session DB has to be cleared before updating.

Why was there a zlib compression but it was removed in the end? I think it might be good to keep a compression. I have read that compressing large fields (which are not accessed in the database directly) may improve performance significantly in some cases. With a larger SATOSA instance, performace might be of great importance.

**Comment by peppelinux** [comment]
@melanger

regarding the breaking change we may suggest to updated the previous definitions instead of deleting them (just a json.dumps in a for loop)

regarding zlib compression, we may think to add this feature as a global parameter.
We decided to avoid compression because mongodb hanldes very well that dump as it is and this, as clear text, would be easy to be matched with a fulltextsearch

would you like to purpose a PR on the dev branch to enable again zlib as an optional global parameter?

**Comment by melanger** [comment]
> would you like to purpose a PR on the dev branch to enable again zlib as an optional global parameter?

If it works for now, let's keep it that way. I may add it later if I hit performance issues.

**Pull request merged**
